### ISSUE TITLE
Issues with showing on the public list

### ISSUE THREAD

**Issue by ImUrX** [Ponjimon/vrising-docker#4]
this is the config im using
```json
{
  "Name": "",
  "Description": "",
  "Port": 25569,
  "QueryPort": 25568,
  "MaxConnectedUsers": 50,
  "MaxConnectedAdmins": 5,
  "ServerFps": 30,
  "SaveName": "",
  "Password": "",
  "Secure": true,
  "ListOnMasterServer": true,
  "AutoSaveCount": 30,
  "AutoSaveInterval": 600,
  "GameSettingsPreset": "",
  "AdminOnlyDebugEvents": true,
  "DisableDebugEvents": false
}
```

I already checked and the 2 ports are being forwarded, and if I add the server to favorites (in the steam server browser) all the info appears but I dont know what to do

I have pings disabled in this server, i dont know if that affects

**Comment by Ponjimon** [comment]
Your config doesn't have a server name so I'm not sure how it should show in the server list? That being said, disable pinging could definitely affect this.

But this has nothing to do with my Docker image as it's more an issue related directly to the server software.
